language: rust

rust:
  - nightly
  - stable
  - beta

addons:
  apt:
    packages:
    - protobuf-compiler

before_script:
  - cargo install protobuf
  - export PATH=$PATH:~/.cargo/bin

script:
  # Run tests for the root crate.
  - cargo test
  # Run tests for all crates in the workspace.
  - for package in $(grep "name" $(find src |grep Cargo.toml) | cut -d ":" -f2 | sed -E 's/.*"(.*)".*/\1/g'); do cargo test -p $package; done
