[package]
name = "cast"
version = "0.1.0"
authors = ["Dylan McKay <dylanmckay34@gmail.com>"]

description = "A library for casting to Google Cast devices"
license = "MIT"
documentation = "https://docs.rs/cast"
repository = "https://github.com/dylanmckay/cast"

keywords = ["cast", "chromecast"]

[dependencies]
mdns = "0.1.2"
uuid = "0.3"
error-chain = "0.6"
